from abc import ABC, abstractmethod


class RobotAdapter(ABC):
    @property
    @abstractmethod
    def entity(self): ...
    @property
    @abstractmethod
    def arm_names(self) -> tuple[str, ...]: ...
    @abstractmethod
    def build(self, scene): ...
    @abstractmethod
    def initialize_after_scene_build(self): ...
    @abstractmethod
    def get_ee_link(self, arm: str): ...
    @abstractmethod
    def get_arm_dofs_idx(self, arm: str): ...
    def get_arm_velocity_limits(self, arm: str): return None
    @abstractmethod
    def get_finger_dofs_idx(self, arm: str): ...
    @abstractmethod
    def get_ee_pose(self, arm: str): ...
    @abstractmethod
    def apply_arm_command(self, arm: str, position, velocity=None): ...
    @abstractmethod
    def apply_gripper_trigger(self, arm: str, trigger: float): ...
    @abstractmethod
    def get_finger_positions(self, arm: str): ...
    @abstractmethod
    def enter_arm_hold(self, arm: str): ...
    @abstractmethod
    def maintain_arm_hold(self, arm: str): ...
    def hold_arm(self, arm: str):
        """Backward-compatible hold entry point."""
        self.enter_arm_hold(arm)
    def hold_all(self):
        for arm in self.arm_names:
            self.hold_arm(arm)
