from abc import ABC, abstractmethod


class RobotAdapter(ABC):
    @property
    @abstractmethod
    def entity(self): ...
    @property
    @abstractmethod
    def arm_names(self) -> tuple[str, ...]: ...
    @abstractmethod
    def build(self, scene): ...
    @abstractmethod
    def initialize_after_scene_build(self): ...
    @abstractmethod
    def get_ee_link(self, arm: str): ...
    @abstractmethod
    def get_arm_dofs_idx(self, arm: str): ...
    @abstractmethod
    def get_finger_dofs_idx(self, arm: str): ...
    @abstractmethod
    def get_ee_pose(self, arm: str): ...
    @abstractmethod
    def apply_arm_position(self, arm: str, q_arm): ...
    @abstractmethod
    def apply_gripper_trigger(self, arm: str, trigger: float): ...
    @abstractmethod
    def get_finger_positions(self, arm: str): ...
    @abstractmethod
    def hold_arm(self, arm: str): ...
    def hold_all(self):
        for arm in self.arm_names:
            self.hold_arm(arm)
